api_port: 8080
clients_port: 50000
registration_port: 50111
actuators_port: 50222
multicast_ip: "224.0.1.0"
multicast_port: 50333
multicast_interval: 2.5
sensors_tolerance: 6.0
actuators_tolerance: 6.0
broker_ip: "localhost"
broker_port: 5672
publish_exchange: "readings"
