# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"#\n\x07\x41\x64\x64ress\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\";\n\nDeviceInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x10\n\x08metadata\x18\x03 \x01(\t\"Q\n\x0bJoinRequest\x12 \n\x0b\x64\x65vice_info\x18\x01 \x01(\x0b\x32\x0b.DeviceInfo\x12 \n\x0e\x64\x65vice_address\x18\x02 \x01(\x0b\x32\x08.Address\"F\n\tJoinReply\x12 \n\x0ereport_address\x18\x01 \x01(\x0b\x32\x08.Address\x12\x17\n\x0freport_interval\x18\x02 \x01(\r\"N\n\rSensorReading\x12\x13\n\x0bsensor_name\x18\x01 \x01(\t\x12\x15\n\rreading_value\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"G\n\rDeviceRequest\x12\x1a\n\x04type\x18\x01 \x01(\x0e\x32\x0c.RequestType\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"6\n\x0b\x44\x65viceReply\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\x12\x0e\n\x06result\x18\x02 \x01(\t*\xb4\x01\n\x0bRequestType\x12\x1b\n\x17REQUESTTYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12REQUESTTYPE_ACTION\x10\x01\x12\x19\n\x15REQUESTTYPE_GET_STATE\x10\x02\x12\x19\n\x15REQUESTTYPE_SET_STATE\x10\x03\x12\x1c\n\x18REQUESTTYPE_GET_METADATA\x10\x04\x12\x1c\n\x18REQUESTTYPE_SET_METADATA\x10\x05*w\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n\tSTATUS_OK\x10\x01\x12\x0e\n\nSTATUS_BAD\x10\x02\x12\x0f\n\x0bSTATUS_FAIL\x10\x03\x12\x11\n\rSTATUS_DENIED\x10\x04\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTTYPE']._serialized_start=481
  _globals['_REQUESTTYPE']._serialized_end=661
  _globals['_STATUS']._serialized_start=663
  _globals['_STATUS']._serialized_end=782
  _globals['_ADDRESS']._serialized_start=18
  _globals['_ADDRESS']._serialized_end=53
  _globals['_DEVICEINFO']._serialized_start=55
  _globals['_DEVICEINFO']._serialized_end=114
  _globals['_JOINREQUEST']._serialized_start=116
  _globals['_JOINREQUEST']._serialized_end=197
  _globals['_JOINREPLY']._serialized_start=199
  _globals['_JOINREPLY']._serialized_end=269
  _globals['_SENSORREADING']._serialized_start=271
  _globals['_SENSORREADING']._serialized_end=349
  _globals['_DEVICEREQUEST']._serialized_start=351
  _globals['_DEVICEREQUEST']._serialized_end=422
  _globals['_DEVICEREPLY']._serialized_start=424
  _globals['_DEVICEREPLY']._serialized_end=478
# @@protoc_insertion_point(module_scope)
