# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/mensagem.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/mensagem.proto\"V\n\x0f\x44ispositivoInfo\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\r\n\x05porta\x18\x04 \x01(\x05\x12\x0e\n\x06\x65stado\x18\x05 \x01(\t\"2\n\x07\x43omando\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x63\x61o\x18\x02 \x01(\t\x12\r\n\x05valor\x18\x03 \x01(\t\"$\n\x06\x45stado\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x65stado\x18\x02 \x01(\t\"K\n\rLeituraSensor\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t\x12\r\n\x05valor\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\";\n\x11ListaDispositivos\x12&\n\x0c\x64ispositivos\x18\x01 \x03(\x0b\x32\x10.DispositivoInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.mensagem_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DISPOSITIVOINFO._serialized_start=25
  _DISPOSITIVOINFO._serialized_end=111
  _COMANDO._serialized_start=113
  _COMANDO._serialized_end=163
  _ESTADO._serialized_start=165
  _ESTADO._serialized_end=201
  _LEITURASENSOR._serialized_start=203
  _LEITURASENSOR._serialized_end=278
  _LISTADISPOSITIVOS._serialized_start=280
  _LISTADISPOSITIVOS._serialized_end=339
# @@protoc_insertion_point(module_scope)
