# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"#\n\x07\x41\x64\x64ress\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\"V\n\nDeviceInfo\x12\x19\n\x04type\x18\x01 \x01(\x0e\x32\x0b.DeviceType\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x10\n\x08metadata\x18\x04 \x01(\t\"Q\n\x0bJoinRequest\x12 \n\x0b\x64\x65vice_info\x18\x01 \x01(\x0b\x32\x0b.DeviceInfo\x12 \n\x0e\x64\x65vice_address\x18\x02 \x01(\x0b\x32\x08.Address\" \n\tJoinReply\x12\x13\n\x0breport_port\x18\x01 \x01(\r\"s\n\rSensorReading\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\x12\x15\n\rreading_value\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x10\n\x08metadata\x18\x04 \x01(\t\x12\x11\n\tis_online\x18\x05 \x01(\x08\"1\n\rSensorsReport\x12 \n\x08readings\x18\x01 \x03(\x0b\x32\x0e.SensorReading\"\x82\x01\n\x0e\x41\x63tuatorUpdate\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63tion_value\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\r\n\x05state\x18\x04 \x01(\t\x12\x10\n\x08metadata\x18\x05 \x01(\t\x12\x11\n\tis_online\x18\x06 \x01(\x08\"3\n\x0f\x41\x63tuatorsReport\x12 \n\x07updates\x18\x01 \x03(\x0b\x32\x0f.ActuatorUpdate\";\n\x0f\x41\x63tuatorCommand\x12\x1a\n\x04type\x18\x01 \x01(\x0e\x32\x0c.CommandType\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\"=\n\x0e\x41\x63tuatorComply\x12\x1d\n\x06status\x18\x01 \x01(\x0e\x32\r.ComplyStatus\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t*:\n\nDeviceType\x12\x12\n\x0e\x44T_UNSPECIFIED\x10\x00\x12\n\n\x06SENSOR\x10\x01\x12\x0c\n\x08\x41\x43TUATOR\x10\x02*K\n\x0b\x43ommandType\x12\x12\n\x0e\x43T_UNSPECIFIED\x10\x00\x12\n\n\x06\x41\x43TION\x10\x01\x12\r\n\tGET_STATE\x10\x02\x12\r\n\tSET_STATE\x10\x03*H\n\x0c\x43omplyStatus\x12\x12\n\x0e\x43S_UNSPECIFIED\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x08\n\x04\x46\x41IL\x10\x02\x12\x12\n\x0eUNKNOWN_ACTION\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICETYPE']._serialized_start=738
  _globals['_DEVICETYPE']._serialized_end=796
  _globals['_COMMANDTYPE']._serialized_start=798
  _globals['_COMMANDTYPE']._serialized_end=873
  _globals['_COMPLYSTATUS']._serialized_start=875
  _globals['_COMPLYSTATUS']._serialized_end=947
  _globals['_ADDRESS']._serialized_start=18
  _globals['_ADDRESS']._serialized_end=53
  _globals['_DEVICEINFO']._serialized_start=55
  _globals['_DEVICEINFO']._serialized_end=141
  _globals['_JOINREQUEST']._serialized_start=143
  _globals['_JOINREQUEST']._serialized_end=224
  _globals['_JOINREPLY']._serialized_start=226
  _globals['_JOINREPLY']._serialized_end=258
  _globals['_SENSORREADING']._serialized_start=260
  _globals['_SENSORREADING']._serialized_end=375
  _globals['_SENSORSREPORT']._serialized_start=377
  _globals['_SENSORSREPORT']._serialized_end=426
  _globals['_ACTUATORUPDATE']._serialized_start=429
  _globals['_ACTUATORUPDATE']._serialized_end=559
  _globals['_ACTUATORSREPORT']._serialized_start=561
  _globals['_ACTUATORSREPORT']._serialized_end=612
  _globals['_ACTUATORCOMMAND']._serialized_start=614
  _globals['_ACTUATORCOMMAND']._serialized_end=673
  _globals['_ACTUATORCOMPLY']._serialized_start=675
  _globals['_ACTUATORCOMPLY']._serialized_end=736
# @@protoc_insertion_point(module_scope)
